version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: femakc/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/foodgram/static/
      - media_value:/app/foodgram/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: femakc/infra_frontend:latest
    volumes:
      - ../frontend/:/app/foodgram/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  db_data:
  static_value:
  media_value: