# Generated by Django 3.0 on 2022-12-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221206_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Breakfast', 'Завтрак'), ('lunch', 'обед'), ('dinner', 'ужин')], help_text='Название тега', max_length=64, unique=True, verbose_name='Название')),
                ('color', models.CharField(choices=[('#553277', 'фиолетовый'), ('#f51100', 'красный'), ('#d3fb00', 'желтый')], help_text='Цвет тега', max_length=64, unique=True, verbose_name='Цвет')),
                ('slug', models.SlugField(help_text='slug тега', max_length=32, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ингредиент рецепта', through='recipes.IngredientProperty', to='recipes.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Тег рецепта', to='recipes.Tag', verbose_name='Тег'),
        ),
    ]
