# Generated by Django 4.1.4 on 2022-12-26 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_remove_favorite_pub_date_alter_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopcart',
            name='user',
            field=models.ForeignKey(help_text='Пользователь корзины', on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
