# Generated by Django 4.1.4 on 2022-12-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tagproperty',
            old_name='tag',
            new_name='tags',
        ),
    ]
