# Generated by Django 4.1.4 on 2022-12-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_tag_recipe_tags_rename_tag_tagproperty_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tagproperty',
            old_name='tags',
            new_name='tag',
        ),
    ]
