# Generated by Django 4.1.4 on 2022-12-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_usershopcart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershopcart',
            name='pub_date',
        ),
    ]
