# Generated by Django 3.0 on 2022-12-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221206_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientproperty',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Количество ингредиента', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления рецепта', verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Цвет тега', max_length=64, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'обед'), ('dinner', 'ужин')], help_text='Название тега', max_length=64, unique=True, verbose_name='Название'),
        ),
    ]
