# Generated by Django 4.1.4 on 2022-12-26 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_usershopcart_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientproperty',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Количество ингредиента', validators=[django.core.validators.MinValueValidator(1, 'Значение должно быть больше нуля.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredientproperty',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredientproperty',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resipe_ingredient', to='recipes.recipe'),
        ),
    ]
