# Generated by Django 3.0 on 2022-12-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221207_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='Цвет тега', max_length=64, verbose_name='Цвет'),
        ),
    ]
