# Generated by Django 3.0 on 2022-12-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221207_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='-', help_text='Цвет тега', max_length=64, unique=True, verbose_name='Цвет'),
        ),
    ]
