# Generated by Django 3.0 on 2022-12-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221207_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Пароль пользователя', max_length=32, verbose_name='Пароль'),
        ),
    ]
