# Generated by Django 4.1.4 on 2022-12-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('anon', 'Аноним'), ('user', 'Аутентифицированный пользователь'), ('admin', 'Администратор')], default='user', help_text='роль', max_length=32, verbose_name='Роль пользователя'),
        ),
    ]
