# Generated by Django 4.1.4 on 2022-12-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Пароль пользователя', max_length=150, verbose_name='Пароль'),
        ),
    ]
